# Window dimensions
INITIAL_WINDOW_WIDTH = 1400
INITIAL_WINDOW_HEIGHT = 800
MIN_WINDOW_WIDTH = 1400
MIN_WINDOW_HEIGHT = 800

# Canvas dimensions
DEFAULT_CANVAS_WIDTH = 800
DEFAULT_CANVAS_HEIGHT = 600

# Animation settings
ANIMATION_STEPS = 20
BASE_ANIMATION_SPEED = 3.0

# Visual settings
NODE_RADIUS = 15
ARRAY_BOX_SIZE = 15
LEFT_MARGIN = 100
TOP_MARGIN = 80
X_SPACING = 50
Y_SPACING = 50

# Colors
NODE_COLOR = "lightblue"
TEXT_COLOR = "black"
MOVING_TEXT_COLOR = "red"

# Fonts
DEFAULT_FONT = "Arial"
DEFAULT_FONT_SIZE = 12
TITLE_FONT_SIZE = 24
HEADING_FONT_SIZE = 16

# File types
JSON_FILETYPES = [("JSON files", "*.json"), ("All files", "*.*")]